/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'simple_code_test.debug+Alif-E7-M55-HP' 
 * Target:  'debug+Alif-E7-M55-HP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.23.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
