

MODEL_REGION_NAME = "WEIGHTS_AND_BIASES_REGION"
SRAM_SCRATCH_REGION_NAME = "SRAM_SCRATCH_REGION"
SRAM_FAST_SCRATCH_REGION_NAME = "SRAM_FAST_SCRATCH_REGION"
INPUT_REGION_NAME = "INPUT_REGION"
OUTPUT_REGION_NAME = "OUTPUT_REGION"